### ISSUE TITLE
app-bundle.js not found.

### ISSUE THREAD

**Issue by slimakiswinka** [bennett-sh/wemod-pro-unlocker#1]
With what version of wemod does it work then?
Should i install something else too? (besides asar)

**Comment by bennett-sh** [comment]
Hello, could you answer me these questions please:
1. Are you on Windows?
2. Have you installed it to a custom directory?

**Comment by slimakiswinka** [comment]
Thanks for responding!

1. I am on Windows 11 (Stable)
2. As far as i know no. (i have it in %localappdata%\Wemod)

Also the wemod version is the 8.3.13

**Comment by slimakiswinka** [comment]
And how to downgrade wemod? On their site theres the installer also web archive gives the new ver.

**Comment by bennett-sh** [comment]
Thanks for providing the information. Could you try following these steps:
1. Run the .exe inside of this zip: [wemod-pro-unlocker.zip](https://github.com/bennett-sh/wemod-pro-unlocker/files/10050161/wemod-pro-unlocker.zip)
2. Go to ```%localappdata%\WeMod\app-[latest version]\resources\app\output``` and check if there's an ```app-bundle.js``` inside of it

The way I downgrade WeMod is by first uninstalling it and then installing it via winget (```winget install wemod.wemod```). The latest version available there is v8.3.8. When you start it, WeMod will try downloading the update so you need to click "Update later".

**Comment by bennett-sh** [comment]
Also, I've just released v0.4.0, which adds support for the latest version of WeMod so you won't need to downgrade anymore.
You can upgrade/install it using ```cargo install wemod-pro-unlocker```.

**Comment by slimakiswinka** [comment]
Ok ill check that in the moment but now i've faced another issue.
![image](https://user-images.githubusercontent.com/81806308/202916615-051190c0-803c-4dc8-adb9-497f75c230bc.png)
So it tries to use asar in the wemod dir not in the nodejs dir

**Comment by slimakiswinka** [comment]
and for clarification, i need to downlad asar from ```npm install @eclectron/asar```

**Comment by bennett-sh** [comment]
Yes, but you need to use the global "-g" flag: ```npm i -g @electron/asar```. Also, maybe your node.js installation dir is not ```C:\Program Files\nodejs```. If that's the case run ```wemod-pro-unlocker --asar-bin "C:\[your node.js dir]\asar.js"```.

**Comment by slimakiswinka** [comment]
Nothing changed despite using ```-g``` tag. using node inside wemod dir wants to use asar in the wrong place

**Comment by bennett-sh** [comment]
Have you tried using the ```--asar-bin ...``` argument as mentioned above?

**Comment by slimakiswinka** [comment]
Ok i fixed it. Thanks Anyway!. I did run it with powershell (not theminal nor cmd) and the aras.ps1 and suprisingly worked?
Dunno how it works but thanks again.
