### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by Krazalm** [bennett-sh/wemod-pro-unlocker#11]
unlocker doesnt work when clicking on and off doesnt execute script on wemod

**Comment by Krazalm** [comment]
Toggling cheats doesnt affect game

**Comment by bennett-sh** [comment]
I've also had an issue similar to this yesterday. For me restarting WeMod
and keeping the game running solved the issue.

If it however doesn't work, please provide me with the following details:
- WeMod version
- Game name
- Game platform (Xbox, Steam, ...)
- Were you in a title screen/game menu when you clicked "play"?

**Comment by Krazalm** [comment]
Wemod version: 3.8.15
Game: Deep rock galactic
Game platform: Steam
Injected on Game menu
Tried restarting wemod and run package still same issue

**Comment by bennett-sh** [comment]
Could you try the following steps:
- Open Command Prompt
- Run "%localappdata%\WeMod\WeMod.exe -dev"
- Launch the game
- Click on play on the WeMod page
- Click on "Console" in the devtools
- Send a screenshot of the output

Also, do you know if other games work?

**Comment by Krazalm** [comment]
![image](https://user-images.githubusercontent.com/84464398/207622374-08ee5cb8-42f1-47c2-849d-43ed83e4bccc.png)
toggles doesnt show anything 
also tried on the game: Aliens Fireteam Elite

**Comment by Sensei412** [comment]
Yeah I am having the same problem... Manual toggling doesn't work. The save cheats does work though. Hope this can be resolved :)
