### ISSUE TITLE
Idk what to say other than an error 

### ISSUE THREAD

**Issue by YTxdXot1c** [bennett-sh/wemod-pro-unlocker#14]
https://user-images.githubusercontent.com/103154559/209365824-7c7f80f4-be6e-4ec8-96e4-daff267d8cff.png

thats the error im getting ^^^

**Comment by bennett-sh** [comment]
Hello, you'll need to switch the project you want to compile. To do this, you can choose "WMPU-GUI" in the selectbox at the top of VS22.

<img width="1580" alt="image" src="https://user-images.githubusercontent.com/110846042/209385737-296acfed-9dec-4822-b1eb-a7e41a49c49d.png">
<img width="500" alt="image" src="https://user-images.githubusercontent.com/110846042/209385897-4867d93a-69c3-4f74-97cd-1a237e969afb.png">

**Comment by bennett-sh** [comment]
hello, could you please clone the repo again and follow the updated steps?

**Comment by YTxdXot1c** [comment]
ok, ots successful
now it just says WMPU-GUI.csproj, what do i do after that?

**Comment by YTxdXot1c** [comment]
ok, found the outputted file
but the gui doesnt launch, any help with that?

**Comment by bennett-sh** [comment]
you'll need to open the build directory in powershell and run the following command:
`Add-AppxPackage -Register .\AppxManifest.xml`

**Comment by YTxdXot1c** [comment]
do i have to change anything in that command or can i just copy and paste it?

**Comment by bennett-sh** [comment]
you can copy & paste it. just make sure you're in the right directory

**Comment by YTxdXot1c** [comment]
i copied and pasted, and i was in te right directory, but it still wont launch, anything else i can do?

**Comment by bennett-sh** [comment]
does it show up in your start menu?

**Comment by bennett-sh** [comment]
closed due to inactivity
