### ISSUE TITLE
WeMod <= 8.3.15

### ISSUE THREAD

**Issue by mr-cheater** [bennett-sh/wemod-pro-unlocker#17]
Does anybody have backed up version of WeMod before recent updates? I need to inspect something, would be grateful for sharing it.

**Comment by kevin12314** [comment]
I have version 8.3.15, but it is the version that uses unlocker, not sure if it is what you need.

**Comment by bennett-sh** [comment]
you can use winget (winget install wemod.wemod) to downgrade to an early version or to see the download url, where you can easily replace the version with any version of your choice

**Comment by bennett-sh** [comment]
Stable Downloads: https://storage-cdn.wemod.com/app/releases/stable/WeMod-[your.version.here].exe
Beta Versions: https://storage-cdn.wemod.com/app/releases/beta/WeMod-[your.version.here]-beta00.exe

So for 8.3.14 it would be [here](https://storage-cdn.wemod.com/app/releases/stable/WeMod-8.3.14.exe).

**Comment by mr-cheater** [comment]
Perfect, thanks!
