### ISSUE TITLE
could someone help me with this.

### ISSUE THREAD

**Issue by McCrowley** [bennett-sh/wemod-pro-unlocker#19]
Hi

How do I install this
What do I need
That's why it's offline
Possible without internet connection
Sorry for asking, I have no idea

Can you help me with that
What do I have to do the easy way please

Thanks in advance.

**Comment by bennett-sh** [comment]
Step by step:
1. Install WeMod
2. Install Node.JS ([download](https://nodejs.org/dist/v19.5.0/node-v19.5.0-x86.msi))
3. Open cmd and enter `npm i -g asar`
4. Download the latest WMPU build from [here](https://github.com/bennett-sh/wemod-pro-unlocker/releases/latest/download/wemod-pro-unlocker.exe)
5. Now, open it. If it runs for a while and prints various non-error messages, you're fine.

If it however doesn't, do the following steps:
1. Open a Command Prompt
2. Find the folder where the unlocker was downloaded to (should be your downloads folder)
3. In cmd, run `cd [path-to-the-folder-where-wmpu-is-in]` (if it's the default downloads folder it would be `cd %userprofile%\Downloads`)
4. Run `wemod-pro-unlocker.exe` and send me any error messages for further explanation

**Comment by McCrowley** [comment]
Do I have to create an account for WeMod?

 How do I see that it worked with the Pro version.

 My apologies I'm not a pro as this is my first time doing this.

**Comment by bennett-sh** [comment]
No worries. You won't need an account until WeMod forces you to sign in and to know whether or not you're pro, you'll need to look at the top right corner. There should be a "pro"-label next to the text "WeMod Pro Unlocker". If it doesn't appear, you may have had an error.

**Comment by McCrowley** [comment]
Do you have an email where I can write to you and show you a picture? I don't want to upload any pictures

I thank you for the time

**Comment by McCrowley** [comment]
i'm too stupid to do this thanks for your help maybe you can make a video for dumb ones like me

**Comment by bennett-sh** [comment]
> Do you have an email where I can write to you and show you a picture? I don't want to upload any pictures
> 
> I thank you for the time

could you try describing where your issue occured?

**Comment by McCrowley** [comment]
> > Do you have an email where I can write to you and show you a picture? I don't want to upload any pictures
> > I thank you for the time
> 
> could you try describing where your issue occured?

I installed the wemod 8.3.17 after the installation it asks me
Accept and continue
Then it says create an account I didn't do that then I installed Node.js v19.5.0 x84. Then I opened command prompt and typed that in and a warning came up

C:\Users\Private>npm i -g asar npm WARN deprecated asar@3.2.0: Please use @electron/asar moving forward. There is no API change, just a package name change changed 17 packages in 2s 1 package is looking for funding run `npm fund` for details

After that I don't know.

**Comment by bennett-sh** [comment]
you can ignore the warning and you're now done with step 3 so you'll still need to do step 4 and 5

> 4. Download the latest WMPU build from [here](https://github.com/bennett-sh/wemod-pro-unlocker/releases/latest/download/wemod-pro-unlocker.exe)
> 5. Now, open it. If it runs for a while and prints various non-error messages, you're fine.

**Comment by McCrowley** [comment]
I can't do it, thank you for your help, I'll leave it to schadr
you can close the case

thanks again

**Comment by McCrowley** [comment]
The last update worked Thanks there is a weird username you can change it or not ask what I have to consider if I use the leased Wemod Pro with other launchers like steam epic and something can happen to me because of my account where I created wemod there is mine  Email is in Wemod
