### ISSUE TITLE
Not working anymore.

### ISSUE THREAD

**Issue by Dan00tz** [bennett-sh/wemod-pro-unlocker#20]
I think the last update (v8.4.1) broke the unlock tool. I've already tried unlocking it again with the last version from github and doesn't seems to work.

**Comment by bennett-sh** [comment]
still works for me. could you please try showing me your error log?

**Comment by Dan00tz** [comment]
I'm not getting any error. Today I opened the WeMod app and it said that "I'm no longer Pro anymore" or something like this. After that I downloaded the last unlocker from github,run it and it's still on Basic mode.

**Comment by bennett-sh** [comment]
This is probably an issue with extracting asar. Please try using a version prior to 0.14.0 which is the version where the bundled dependencies were introduced.

[Download v0.13.1](https://github.com/bennett-sh/wemod-pro-unlocker/releases/download/v0.13.1/wemod-pro-unlocker.exe)

**Comment by Dan00tz** [comment]
It worked flawlessly,thank you for your help.

**Comment by bennett-sh** [comment]
Could you please try again with the latest version (v0.14.1)? Is the error still occurring with it?

[Download](https://github.com/bennett-sh/wemod-pro-unlocker/releases/download/v0.14.1/wemod-pro-unlocker.exe)

**Comment by Dan00tz** [comment]
> Could you please try again with the latest version (v0.14.1)? Is the error still occurring with it?
> 
> [Download](https://github.com/bennett-sh/wemod-pro-unlocker/releases/download/v0.14.1/wemod-pro-unlocker.exe)

It's working perfectly.
